### ISSUE TITLE
ExternalSeqRecordParser model and ExternalRecordParser model run error，why？

### ISSUE THREAD

**Issue by niuzhi** [Isaac-DeFrain/TLAplusFun#24]
Hello，I am using TLA+ to implement trace verification, and found that you have provided two interfaces ExternalSeqRecordParser and ExternalRecordParser, but I am running these two interfaces and report an error, what is the reason for this, and I look forward to your reply.

ExternalRecordParser 
connect.log
a : 42, b : true
a : -1, b : false
a : 0, b : true
![image](https://user-images.githubusercontent.com/33443724/154607921-bac6a98a-938f-429b-a0b1-d3223f56a96b.png)

ExternalRecordParser 
connect.log
a : 42
b : true
![image](https://user-images.githubusercontent.com/33443724/154608616-2e8b36ad-3ef3-4ac5-82d3-c69428309a73.png)

**Comment by Isaac-DeFrain** [comment]
Thank you for reporting the errors. I am currently traveling so it will be a few days before I can investigate. I look forward to resolving the issues!

**Comment by Isaac-DeFrain** [comment]
What version of the tools are you using? There is a jar file provided in the repo. Everything should work if you run it with that version.

**Comment by Isaac-DeFrain** [comment]
Aha! It must be related to [this](https://github.com/tlaplus/CommunityModules/issues/53)
