### ISSUE TITLE
Contribute External*Parser to CommunityModules

### ISSUE THREAD

**Issue by lemmy** [Isaac-DeFrain/TLAplusFun#25]
Hi, we recently added generic (de-)serialization to the IOUtils module of the CommunityModules (https://github.com/tlaplus/CommunityModules/issues/53).  Perhaps, you want to contribute your parser to the CommunityModules, too?

**Comment by Isaac-DeFrain** [comment]
Sorry for the delay. Yes, of course! I think that change may have caused TLC to throw errors for the current version. I'll make the necessary changes and then add it to the community modules :)

**Comment by Isaac-DeFrain** [comment]
https://github.com/tlaplus/CommunityModules/pull/75
