### ISSUE TITLE
GreenLeftOfWhite in Einstein Riddle seems wrong

### ISSUE THREAD

**Issue by leuschel** [Isaac-DeFrain/TLAplusFun#4]
I think it should be
```
GreenLeftOfWhite == \E i \in 1..4 : colors[i] = "green" /\ colors[i+1] = “white"
```

**Comment by Isaac-DeFrain** [comment]
You are absolutely right. I originally made this mistake and found no solution, surprise, surprise... I corrected it and made some further simplifications and apparently copied the wrong file into this repo. Thank you for catching that!

**Comment by Isaac-DeFrain** [comment]
The simplification I alluded to is
```
NorwegianLivesNextToBlueHouse == colors[2] = "blue"
```
since we already know that the Norwegian is in the first house.
